// This file is generated by Slice Machine. Update with care!

import Bibliography from './Bibliography';
import Carousel from './Carousel';
import Gallery from './Gallery';
import Image from './Image';
import LeadText from './LeadText';
import MainText from './MainText';

export {
	Bibliography,
	Carousel,
	Gallery,
	Image,
	LeadText,
	MainText,
};

export const components = {
	bibliography: Bibliography,
	carousel: Carousel,
	gallery: Gallery,
	image: Image,
	lead_text: LeadText,
	main_text: MainText,
};
