// This file is generated by Slice Machine. Update with care!

import Announcements from './Announcements';
import Carousel from './Carousel';
import LeadText from './LeadText';
import MainText from './MainText';

export {
	Announcements,
	Carousel,
	LeadText,
	MainText,
};

export const components = {
	announcements: Announcements,
	carousel: Carousel,
	lead_text: LeadText,
	main_text: MainText,
};
